### ISSUE TITLE
No license in the template

### ISSUE THREAD

**Issue by haesleinhuepf** [HenriquesLab/LiquidEngineCookieCutter#1]
After using the cookiecutter template, the newly created folder contains an empty license file. Maybe checkout how the napari-plugin-template deals with licenses:

https://github.com/napari/cookiecutter-napari-plugin/blob/d6efeb2ae43f04cc7a907e5743721ccef35fea99/%7B%7Bcookiecutter.plugin_name%7D%7D/LICENSE

**Comment by antmsbrito** [comment]
Thanks for the idea to check out napari-cookiecutter! We've followed their footsteps and implemented the same approach to select a license.
