### ISSUE TITLE
Python coding conventions in naming

### ISSUE THREAD

**Issue by haesleinhuepf** [HenriquesLab/LiquidEngineCookieCutter#2]
I recommend following Python conventions in naming things. For example, after running the cookiecutter with default values, a package/module folder is created named "MyLEPackage". According to [PEP 8 – Style Guide for Python Code](https://peps.python.org/pep-0008/#package-and-module-names) this should all be lowercase.

**Comment by antmsbrito** [comment]
Hello thanks for the catch :) 

The default name is now lowercase and we know enforce the name to follow PEP 8 (akin to [napari-cookiecutter](https://github.com/napari/cookiecutter-napari-plugin/blob/main/hooks/pre_gen_project.py))
