### ISSUE TITLE
Tests in the template

### ISSUE THREAD

**Issue by haesleinhuepf** [HenriquesLab/LiquidEngineCookieCutter#3]
The template contains a [test.py](https://github.com/HenriquesLab/LiquidEngineCookieCutter/blob/main/%7B%7Bcookiecutter.directory_name%7D%7D/test.py) which contains some code (not sure for what use-case). Anyway, it might be great to use established test-frameworks for testing, e.g. [pytest](https://docs.pytest.org/en/8.0.x/). Check out how the napari-folks propose testing in their cookiecutter template [here](https://github.com/napari/cookiecutter-napari-plugin/tree/d6efeb2ae43f04cc7a907e5743721ccef35fea99/%7B%7Bcookiecutter.plugin_name%7D%7D/src/%7B%7Bcookiecutter.module_name%7D%7D/_tests) and for the corresponding github-CI [here](https://github.com/napari/cookiecutter-napari-plugin/tree/d6efeb2ae43f04cc7a907e5743721ccef35fea99/%7B%7Bcookiecutter.plugin_name%7D%7D/.github/workflows) and [here](https://github.com/napari/cookiecutter-napari-plugin/blob/d6efeb2ae43f04cc7a907e5743721ccef35fea99/%7B%7Bcookiecutter.plugin_name%7D%7D/tox.ini).

**Comment by antmsbrito** [comment]
Following your suggestion we removed the old test and implemented a pytest approach. We also added nox support to show how to use it to automate the testing for different python versions and added a github action workflow. 
Thanks for the suggestions!
